logging:
  level:
    org:
      springframework: DEBUG

spring:
  redis:
    host: redis
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres